# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

codecov: true

os:
  - osx
  - linux

julia:
  - 1.0
  - 1.1
  - nightly

matrix:
  allow_failures:
  - julia: nightly

after_success:
  # push coverage results to Codecov
  # - julia -e 'using Pkg; cd(Pkg.dir("GeoRasters")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # build documentation
  - julia -e 'using Pkg; Pkg.add("Documenter"); using GeoRasters; cd(Pkg.dir("GeoRasters")); include(joinpath("docs", "make.jl"))'
